"""empty message

Revision ID: 15158db962ea
Revises: e5936747311d
Create Date: 2022-08-18 20:49:51.646197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15158db962ea'
down_revision = 'e5936747311d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
