"""Changed the Shows start time to string

Revision ID: 563f9a439d0e
Revises: f85921930a7d
Create Date: 2022-08-14 11:46:33.712724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563f9a439d0e'
down_revision = 'f85921930a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
