"""empty message

Revision ID: 940ddae564eb
Revises: eae07b44788e
Create Date: 2022-08-14 02:39:26.765539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940ddae564eb'
down_revision = 'eae07b44788e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
