"""Corrected the lowercase Column

Revision ID: dda7a1ca7a04
Revises: f2b849ffb71f
Create Date: 2022-08-13 20:14:00.669172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda7a1ca7a04'
down_revision = 'f2b849ffb71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows_count')
    op.drop_column('Artist', 'past_shows_count')
    # ### end Alembic commands ###
